//
// Created by Yishiyu on 2020/11/3.
//

#ifndef MINECRAFT_YISHIYU_EDITION_WORLDCONSTANTS_H
#define MINECRAFT_YISHIYU_EDITION_WORLDCONSTANTS_H

// 声明为字面量
constexpr int CHUNK_SIZE = 16;
constexpr int CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE;
constexpr int CHUNK_VOLUME = CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE;


#endif //MINECRAFT_YISHIYU_EDITION_WORLDCONSTANTS_H
