//
// Created by Yishiyu on 2020/11/3.
//

#ifndef MINECRAFT_YISHIYU_EDITION_WORLDCONSTANTS_H
#define MINECRAFT_YISHIYU_EDITION_WORLDCONSTANTS_H

// 声明为字面量
constexpr int SECTION_SIZE = 16;
constexpr int SECTION_AREA = SECTION_SIZE * SECTION_SIZE;
constexpr int SECTION_VOLUME = SECTION_SIZE * SECTION_SIZE * SECTION_SIZE;


#endif //MINECRAFT_YISHIYU_EDITION_WORLDCONSTANTS_H
